

export EM_CMAKE_PATH=/home/mensheng/app/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

sed -i 's/set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)/#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)/' \
  ${EM_CMAKE_PATH}
sed -i 's/set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)/#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)/' \
  ${EM_CMAKE_PATH}
sed -i 's/set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)/#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)/' \
  ${EM_CMAKE_PATH}